name: Tests

on:
  push:

jobs:
  disjoint_set:
    name: Disjoint Set
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build tests
        run: gcc -Wall -Wextra -o u_tests test_disjoint_set.c disjoint_set.c
      - name: Run tests
        run: ./u_tests
